project:
  type: website
  output-dir: .

website:
  title: "Report"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: graphs/visnetwork_tmp.html
        text: VisNetork Visualisation
      - href: graphs/index.html
        text: Gephi Graph Visualisation
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
